version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:  
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - towtier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: mydb
    networks:
      - towtier
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:

networks:
  towtier:
